Remove float more actions
halo-dev/halo-admin pull request #245
Opened 2020-09-13 13:58 UTC by JohnNiang

2020-09-13 15:31 UTC, ruibaby requested changes

2020-09-13 15:31 UTC, ruibaby commented on src/views/interface/ThemeList.vue
> +<style lang="less" scoped>
class="flex justify-center items-center h-24"

2020-09-15 03:02 UTC, ruibaby commented
我觉得使用这个更好。https://www.antdv.com/components/page-header-cn/

2020-09-18 15:20 UTC, JohnNiang commented
> 我觉得使用这个更好。https://www.antdv.com/components/page-header-cn/

尝试一下。

2020-09-19 13:58 UTC, ruibaby approved these changes

2020-09-19 13:58 UTC, merged