refactor: post editing
halo-dev/halo-admin pull request #439
Opened 2022-02-16 09:27 UTC by ruibaby

Signed-off-by: Ryan Wang <i@ryanc.cc>

2022-02-16 12:48 UTC, guqing commented
ctrl+ s / command + s 保存时建议增加一个message提示来让用户知道保存已经生效

2022-02-17 07:28 UTC, guqing commented
发布后重新点进去控制台会报错：
<img width="445" alt="image" src="https://user-images.githubusercontent.com/38999863/154426325-e6c6293f-c42a-422d-9aa8-f61f1e1c3b48.png">

2022-02-17 07:31 UTC, ruibaby commented
@guqing donw

2022-02-17 07:46 UTC, guqing commented
保存内容后应该重新获取 isInProgress的值赋值给前端变量用于展示
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/38999863/154428939-dc9a3cdb-0af6-4b76-850f-3a02f8a018e9.png">

2022-02-17 08:06 UTC, guqing requested changes

2022-02-17 08:06 UTC, guqing commented on src/views/post/PostEdit.vue
> +        this.postToStage.isInProcess = true
这里直接用接口返回来的 ·isInProcess· 值吧

2022-02-17 08:13 UTC, ruibaby commented on src/views/post/PostEdit.vue
> +        this.postToStage.isInProcess = true
Done

2022-02-17 08:14 UTC, guqing approved these changes
LGTM

2022-02-18 02:47 UTC, ruibaby commented
/cc @JohnNiang

2022-02-18 05:16 UTC, guqing commented
@ruibaby 上游PR做了更改，现在需要将`isInProcess`改为 `inProgress`

2022-02-18 05:25 UTC, ruibaby commented
> 

已修改。

2022-02-18 05:26 UTC, guqing approved these changes

2022-02-20 14:38 UTC, merged