perf: add no cache param for attachment list images
halo-dev/halo-admin pull request #491
Opened 2022-03-08 03:29 UTC by ruibaby

Close #488 

给附件列表的图片添加 no cache 的路径参数，保证每次刷新都会更新图片内容。不仅是 #488 中遇到了这种问题，实际上在页码切换也会有延迟更新图片的表现。

Signed-off-by: Ryan Wang <i@ryanc.cc>

2022-03-08 03:55 UTC, guqing approved these changes

2022-03-08 04:36 UTC, JohnNiang reviewed
HTTP 缓存的问题用 Header 来控制是不是会更好些呢？

参考：
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#the_cache-control_header

2022-03-08 04:40 UTC, ruibaby commented
> HTTP 缓存的问题用 Header 来控制是不是会更好些呢？
> 
> 参考：
> 
> * https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#the_cache-control_header

那么需要在哪里设置以及设置的范围呢？

2022-03-08 04:56 UTC, ruibaby reviewed
没有考虑云存储加了图片处理规则的情况。

2022-03-08 04:57 UTC, guqing requested changes
针对链接中已有?参数的url做处理

2022-03-09 10:12 UTC, JohnNiang approved these changes

2022-03-09 10:24 UTC, closed without merging