feature: 添加编译时生成静态gz文件
halo-dev/halo-admin pull request #547
Opened 2022-04-11 08:24 UTC by 2211898719

直接编译时生成现成的gzip压缩文件，可以降低服务器动态压缩负载

2022-04-11 08:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=547) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=547) before we can accept your contribution.<br/><hr/>**hongjunlong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=547) it.</sub>

2022-04-11 09:51 UTC, ruibaby requested changes

2022-04-11 09:51 UTC, ruibaby commented on package.json
> +    "compression-webpack-plugin": "^9.2.0",
应该放在 devDependencies

2022-04-11 09:51 UTC, ruibaby commented
你好 @2211898719 ，感谢你的贡献，你可能需要先按照 https://github.com/halo-dev/halo-admin/pull/547#issuecomment-1094699784 的提示 sign 一下我们的 CLA。

2022-04-11 09:54 UTC, ruibaby commented
/kind feature

2022-04-11 10:21 UTC, 2211898719 commented on package.json
> +    "compression-webpack-plugin": "^9.2.0",
你说的对!!!

2022-04-11 10:23 UTC, ruibaby commented on package.json
> +    "compression-webpack-plugin": "^9.2.0",
修改之后直接推送到这个分支就行了。

2022-04-11 10:28 UTC, 2211898719 commented on package.json
> +    "compression-webpack-plugin": "^9.2.0",
已经提交了

2022-04-11 11:59 UTC, ruibaby commented
/retitle feat: generate gzip products at build time

2022-04-11 12:24 UTC, ruibaby commented
> > 
> 
> 我第一次commit使用的是公司的邮箱，好像没有对应的github账号 该怎么处理

现在提示的什么呢

2022-04-11 12:26 UTC, 2211898719 commented
> > > 
> > 
> > 
> > 我第一次commit使用的是公司的邮箱，好像没有对应的github账号 该怎么处理
> 
> 现在提示的什么呢

两次commit有一个未签署 可能得明天到公司 用公司邮箱注册下github 然后就可以认证了

2022-04-11 12:26 UTC, ruibaby commented
> > > > 
> > > 
> > > 
> > > 我第一次commit使用的是公司的邮箱，好像没有对应的github账号 该怎么处理
> > 
> > 
> > 现在提示的什么呢
> 
> 两次commit有一个未签署 可能得明天到公司 用公司邮箱注册下github 然后就可以认证了


你可以这样操作：

```
git reset --soft upstream/master

git add .

git commit -a -s -m "feat: generate gzip products at build time"

git push -f
```

commit 的时候注意用自己的号就行了。

2022-04-11 12:27 UTC, ruibaby commented
> 两次commit有一个未签署 可能得明天到公司 用公司邮箱注册下github 然后就可以认证了

也可以的。

2022-04-11 13:08 UTC, ruibaby requested changes

2022-04-11 13:08 UTC, ruibaby commented on package.json
> +    "compression-webpack-plugin": "^9.2.0",
这里在你 force push 之后似乎被改回去了。

2022-04-11 13:49 UTC, ruibaby requested changes

2022-04-11 13:49 UTC, ruibaby commented on pnpm-lock.yaml
> +      '@vue/vue-loader-v15': registry.npmmirror.com/vue-loader/15.9.8_b9027617f4ed1744c121688a6a6ed625
不建议修改 pnpm-lock.yaml 的 npm 镜像源。

2022-04-11 13:58 UTC, 2211898719 commented on pnpm-lock.yaml
> +      '@vue/vue-loader-v15': registry.npmmirror.com/vue-loader/15.9.8_b9027617f4ed1744c121688a6a6ed625
pnpm-lock不应该是在pnpm install的时候生成的吗，不是不应该提交到代码仓库，是为了控制源吗

2022-04-11 14:01 UTC, ruibaby commented on pnpm-lock.yaml
> +      '@vue/vue-loader-v15': registry.npmmirror.com/vue-loader/15.9.8_b9027617f4ed1744c121688a6a6ed625
> pnpm-lock不应该是在pnpm install的时候生成的吗，不是不应该提交到代码仓库，是为了控制源吗

对，但这个提交把 mirror 改了，这会影响到我们的 CI。

2022-04-11 14:11 UTC, 2211898719 commented
抱歉 不是非常清楚你们的开发设置 所以有点菜 哈哈

2022-04-11 14:11 UTC, ruibaby commented
@2211898719 感谢你的贡献，这个 PR 将被合并。

2022-04-11 14:49 UTC, merged

2022-04-28 06:04 UTC, ruibaby commented
/milestone 1.6.x