perf: The Save button in the theme setting page is placed at the top（#546）
halo-dev/halo-admin pull request #549
Opened 2022-04-14 15:26 UTC by Aanko

主题设置页面顶部添加了个保存设置按钮

before：
![1649948665770](https://user-images.githubusercontent.com/28836989/163418768-cdc3d703-65f2-483d-8bbd-dd94d59ca2a2.jpg)

after:
![1649949838184](https://user-images.githubusercontent.com/28836989/163422262-916fd130-d308-482c-971d-10fe3c6d0db2.jpg)

2022-04-14 15:31 UTC, ruibaby commented
/retitle perf: add a button to save the settings in the actions area of the theme settings page

2022-04-14 15:32 UTC, ruibaby commented
/kind feature
/cc @halo-dev/sig-halo-admin

2022-04-14 15:32 UTC, ruibaby commented
/milestone 1.5.x

2022-04-15 02:57 UTC, ruibaby requested changes
感觉这样的实现方式对 ThemeSettingForm 的入侵性有点高，可以探索一下更好的解决方式。

2022-04-17 03:34 UTC, ruibaby reviewed
/lgtm

2022-04-17 03:37 UTC, guqing reviewed
/approve

2022-04-17 04:00 UTC, QuentinHsu commented
/approve

2022-04-17 11:43 UTC, ruibaby approved these changes

2022-04-17 11:44 UTC, merged

2022-04-28 06:05 UTC, ruibaby commented
/milestone 1.6.x