添加starttls的按钮
halo-dev/halo-admin pull request #552
Opened 2022-04-19 14:41 UTC by ntdgy

**What this PR do**
添加开启starttls的按钮。
后端修改的对应pr为: https://github.com/halo-dev/halo/pull/1861

2022-04-19 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=552) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=552) it.</sub>

2022-04-19 14:50 UTC, JohnNiang reviewed
I'm going to hold this PR until https://github.com/halo-dev/halo/pull/1861 got merged.
/hold

2022-04-20 06:13 UTC, ruibaby requested changes

2022-04-20 06:13 UTC, ruibaby commented on src/views/system/optiontabs/SmtpTab.vue
> +          <a-form-model-item label="是否启用starttls：">
```suggestion
          <a-form-model-item label="启用 STARTTLS：">
```

2022-04-20 06:13 UTC, ruibaby commented
/unhold

/cc @halo-dev/sig-halo-admin

2022-04-20 06:15 UTC, ruibaby commented
/retitle feat: SMTP support configuration starttls

/kind feature
/milestone 1.5.x

2022-04-20 06:16 UTC, ruibaby commented on src/views/system/optiontabs/SmtpTab.vue
> +          <a-form-model-item label="是否启用starttls：">
这似乎是专有名词，建议按照对其的命名规范来。

https://zh.wikipedia.org/wiki/STARTTLS

2022-04-20 09:59 UTC, ntdgy commented on src/views/system/optiontabs/SmtpTab.vue
> +          <a-form-model-item label="是否启用starttls：">
已经修改，谢谢提醒

2022-04-20 10:00 UTC, ruibaby approved these changes

2022-04-20 10:01 UTC, guqing reviewed
/approve

2022-04-20 10:02 UTC, merged

2022-04-28 06:05 UTC, ruibaby commented
/milestone 1.6.x