feat: Add remove EXIF button
halo-dev/halo-admin pull request #554
Opened 2022-04-24 09:26 UTC by SladeGranger

**What this PR does？**

添加是否去除图片EXIF选项的按钮。
后端修改的对应pr为: https://github.com/halo-dev/halo/pull/1889

2022-04-24 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=554) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=554) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=554) it.</sub>

2022-04-24 09:48 UTC, JohnNiang commented
Hold this PR until upstream PR https://github.com/halo-dev/halo/pull/1889 got merged.
/hold

2022-04-24 12:43 UTC, ruibaby requested changes
/hold

等待 https://github.com/halo-dev/halo/pull/1889 完成合并。

2022-04-24 12:43 UTC, ruibaby commented on src/views/system/optiontabs/AttachmentTab.vue
> +      <a-form-model-item label="是否去除图片EXIF：">
```suggestion
      <a-form-model-item label="去除图片 EXIF 信息：">
```

2022-06-21 13:24 UTC, JohnNiang reviewed
> https://github.com/halo-dev/halo/pull/2168 已经合并

/lgtm

2022-06-21 13:24 UTC, ruibaby reviewed
/approve

2022-06-21 13:25 UTC, ruibaby commented
/milestone 1.6.x

2022-06-21 13:56 UTC, ruibaby approved these changes

2022-06-21 13:58 UTC, merged