fix #2090
halo-dev/halo-admin pull request #573
Opened 2022-05-21 13:36 UTC by ETLAN666

#### What type of PR is this?
/kind improvement

#### What this PR does / why we need it:
在上传本地文件时，可以过滤不支持上传的文件类型的文件
#### Which issue(s) this PR fixes:

Fixes #2090

#### Screenshots:

#### Special notes for your reviewer:
accepts= ['.md', '.txt']   限制了支持上传的文件类型为markdown和txt，在浏览本地文件时，只会显示这两类型的文件
#### Does this PR introduce a user-facing change?

```release-note
```

2022-05-21 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=573) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=573) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=573) it.</sub>

2022-05-24 11:27 UTC, ruibaby requested changes
@ETLAN666 你好，感谢你的贡献，这里有几个问题，有时间可以看看。

2022-05-24 17:01 UTC, ETLAN666 commented
谢谢指点&nbsp; 我会再完善




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 晚上7:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo-admin] fix #2090 (PR #573)





 
@ruibaby requested changes on this pull request.
 
@ETLAN666 你好，感谢你的贡献，这里有几个问题，有时间可以看看。

 
In src/components/Upload/FilePondUpload.vue:
 &gt; @@ -64,7 +65,8 @@ export default {        type: Array,        required: false,        default: () =&gt; { -        return null +        return ['.md', '.txt']  
不应该在修改上传组件的格式限制默认值，应该在 Markdown 导入使用的地方传参数。https://github.com/halo-dev/halo-admin/blob/2e3959bd12839d34da02142b5964d730ba12af4d/src/views/system/ToolList.vue#L53-L58
 
 
In src/components/Upload/FilePondUpload.vue:
 &gt; @@ -3,6 +3,7 @@      <file-pond        ref="pond"        :accepted-file-types="accepts" +      :allowFileTypeValidation="fileTypeCheck"  
添加这个参数的目的是？希望系统一下相关文档。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-05-25 01:19 UTC, ETLAN666 commented on src/components/Upload/FilePondUpload.vue
> +      :allowFileTypeValidation="fileTypeCheck"
这里添加这个参数的想法是想禁用文件类型校验方法，因为自己在修改测试中发现对上传组件可接受文件类型进行限制后（点击上传，浏览本地文件 自动过滤不显示后缀不为 .md, .txt 的 文件），再使用FileTyeValidation会出现一些问题，比如上传文件为markdown文件， 但校验会报错，提示说不是.md 文件，当时觉得既然限制了过滤了上传可选文件，也就没必要使用FileTyeValidation，便把fileTyeCheck设置为 false，这样修改后，刚才提到的冲突也不存在了

2022-05-25 01:26 UTC, ETLAN666 commented on src/components/Upload/FilePondUpload.vue
> +        return ['.md', '.txt']
目前是后端也做出了对应修改，会对上传过来的文件进行类型校验，只支持markdown  txt文件，所以前端这里我对应做出了限制，想要防止用户误传其他格式文件，觉得更合理的方法是在浏览上传的时候，只过滤显示 .md  .txt这两种格式的文件会更好，得是否在两个地方都限制默认值会更好？上传组件 以及 Markdown导入的地方？

2022-05-25 02:20 UTC, JohnNiang reviewed
若后端限制了文件上传的类型且允许用户**自行配置**，这里就没有必要限制了。

2022-05-25 04:42 UTC, ETLAN666 commented
> 
嗯，那就只有markdown导入使用的组件那里可以加一下限制

2022-07-12 15:08 UTC, JohnNiang commented
Hi @ETLAN666 ，这个功能已经在后端完成，请参考：
- https://github.com/halo-dev/halo/pull/2104
- https://github.com/halo-dev/halo/pull/2187

我将关闭此 PR。如果有任何问题，请随时重新打开它。

/close

2022-07-12 15:08 UTC, closed without merging