Feat: 重构LinkList.vue以支持友链和分组的拖拽排序
halo-dev/halo-admin pull request #574
Opened 2022-05-22 08:38 UTC by gungnir479

refactor LinkList.vue, use Vue.Draggable to sort links and teams via dragging

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
使用Vue.Draggable重构了友链功能。现在可以通过可视化拖拽对友链或整个分组进行排序。支持友链移入/移出分组。
#### Which issue(s) this PR fixes:

Fixes # 1905

#### Screenshots:

演示视频：
<video src="https://user-images.githubusercontent.com/65994555/169685416-e4b86306-bd96-4e5a-bbde-d40f6383d9ca.mp4"></video>

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
重构了管理友链的界面，现在可以通过拖拽的形式可视化的管理友链及友链分组的排序
```

2022-05-22 08:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=574) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=574) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=574) it.</sub>

2022-05-24 02:36 UTC, ruibaby commented
你好 @gungnir479 ，感谢你的贡献，我认为这个 UI 可能需要改进一下，这种形式无法完整显示出单个友链的完整信息，至少需要展示站点链接、站点名称。我认为可以参考一下：https://ryanc.cc/links.html

2022-05-25 09:14 UTC, gungnir479 commented
> 你好 @gungnir479 ，感谢你的贡献，我认为这个 UI 可能需要改进一下，这种形式无法完整显示出单个友链的完整信息，至少需要展示站点链接、站点名称。我认为可以参考一下：https://ryanc.cc/links.html

Hi, @ruibaby [ruibaby](https://github.com/ruibaby)，已经修改了UI，现在会显示友链的logo，名称和简介。效果如下：

![halo](https://user-images.githubusercontent.com/60775260/170227278-2d1e629a-8208-4f0e-ab2b-49066a4d9892.png)


>

2022-05-27 05:29 UTC, ruibaby requested changes
感谢你的贡献，我这里有几个问题，有时间可以看看。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +    <a-modal :visible="modal.visible" title="确定移出分组吗" @ok="removeTeam" @cancel="recoverTeam">
添加/修改的表单弹窗建议与新建分类弹框的布局一致。并封装成组件，参考：https://github.com/halo-dev/halo-admin/blob/master/src/components/Category/CategoryCreateModal.vue

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                              <a-tag class="link" style="height: 50px; width: 150px; display: flex; justify-content: space-around; align-items: center">
不要使用 `a-tag` 组件来做布局，且下方的 `a-card-meta` 组件用法不规范，他的上级节点应该是 `a-card`。

关于布局和 UI，我这里有一个参考，并不一定要使用 antd 的组件来布局。

```html
<div class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
  <a href="https://ryanc.cc" target="_blank">
    <div class="relative flex items-center space-x-3 rounded border border-gray-300 bg-white px-5 py-4 shadow-sm hover:border-gray-400 hover:shadow">
      <div class="flex-shrink-0">
        <img class="h-12 w-12 rounded-full" src="https://ryanc.cc/avatar" />
      </div>
      <div class="min-w-0 flex-1">
        <div>
          <p class="truncate text-sm font-medium text-gray-900">Ryan Wang's Blog</p>
          <p class="truncate text-sm text-gray-500">这是一段描述</p>
        </div>
      </div>
      <div class="absolute top-0 right-0">
        <!-- 操作按钮，替换成图标 -->
        <div>拖动</div>
        <div>更多</div>
      </div>
    </div>
  </a>
</div>
```

可以在 https://play.tailwindcss.com/Yu7ppXtnn5 中查阅效果。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                            <a-popover
我建议不使用 popover 来展示编辑和删除的按钮，可以参考下面的代码。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -          <a-input v-model="optionsModal.data.links_title" />
这是一段不必要地修改，建议配置一下 `Prettier` `ESLint` `EditorConfig` `Volar` 插件。如果你是使用的 VS Code，应该不需要手动去配置。但需要安装好这几个插件。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +    <a-modal >
测试的代码需要删除。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +import {PageView} from '@/layouts'
同上，不必要地格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -    scopedSlots: { customRender: 'name' }
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -    scopedSlots: { customRender: 'url' }
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -    scopedSlots: { customRender: 'action' }
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +      drag: false,
这个 drag 的值似乎没有变化过，我只看到了 https://github.com/halo-dev/halo-admin/pull/574/files#diff-c21a683c9d26ae62c62935a90cdf536c2f40970ce7c73eddb2d8b06ce23a980cR89 在使用，是否需要定义一个变量？

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -            { required: true, message: '* 友情链接名称不能为空', trigger: ['change'] },
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -            { required: true, message: '* 友情链接地址不能为空', trigger: ['change'] },
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> -          logo: [{ max: 1023, message: '* 友情链接 Logo 的字符长度不能超过 1023', trigger: ['change'] }],
同上，格式化问题。

2022-05-27 05:29 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +    updatePriority() {
建议用 `handleUpdateInBatch`

2022-05-27 05:36 UTC, ruibaby commented
另外，还有一个布局的建议：

可以将添加按钮放在页面的 Page Header 里面，然后每个组的链接放在一个 Card 里面，如图所示。

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/21301288/170636370-0469c523-387a-435b-8341-09ee039fa604.png">

2022-05-27 10:03 UTC, ruibaby commented
`@halo-dev/admin-api` 包已经更新到 1.1.0，包含了这个 PR https://github.com/halo-dev/js-sdk/pull/40

可以更新一下。

2022-05-28 06:53 UTC, gungnir479 commented on src/views/sheet/independent/LinkList.vue
> +                            <a-popover
你好，请问是不是忘记放代码了？😂

2022-05-28 06:59 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                            <a-popover
> 你好，请问是不是忘记放代码了？😂

https://github.com/halo-dev/halo-admin/pull/574#discussion_r883279277

2022-06-01 05:54 UTC, ruibaby reviewed
关于布局，我这里有一个简单的修改，可以探讨一下。

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/21301288/171337020-8c18f4eb-1252-46e1-ad23-c640ae42bdee.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/21301288/171337046-0e519700-c484-4889-b4a4-f2d7d73318ff.png">



变动：https://github.com/ruibaby/halo-admin/commit/19f03c2e70c698b985fbffbee81afcbe7193bc9d#diff-c21a683c9d26ae62c62935a90cdf536c2f40970ce7c73eddb2d8b06ce23a980c

2022-06-01 05:54 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +    <a-modal :visible="modal.visible" title="确定移出分组吗" @ok="removeTeam" @cancel="recoverTeam">
这种类型的弹框可以使用 API 来调用。参考：https://1x.antdv.com/components/modal-cn/#%E7%A1%AE%E8%AE%A4%E5%AF%B9%E8%AF%9D%E6%A1%86

2022-06-01 05:54 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                      <div class="flex-col absolute top-0 right-0" style="justify-content: center">
建议使用图标代替文字。

2022-06-01 05:59 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +            group="pull: 'false', put: false"
这个写法有相关文档吗？建议提供一下。

2022-06-03 07:34 UTC, gungnir479 commented on src/views/sheet/independent/LinkList.vue
> +            group="pull: 'false', put: false"
主要参考了Vue.Draggable的文档：
https://github.com/SortableJS/Vue.Draggable
handle和group属性可以参考Sortable文档的相关部分：
https://github.com/SortableJS/Sortable#handle-option
https://github.com/SortableJS/Sortable#group-option

2022-06-03 08:20 UTC, gungnir479 commented
> 关于布局，我这里有一个简单的修改，可以探讨一下。
> 
> <img alt="image" width="1524" src="https://user-images.githubusercontent.com/21301288/171337020-8c18f4eb-1252-46e1-ad23-c640ae42bdee.png">
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/21301288/171337046-0e519700-c484-4889-b4a4-f2d7d73318ff.png">
> 
> 变动：[ruibaby@19f03c2#diff-c21a683c9d26ae62c62935a90cdf536c2f40970ce7c73eddb2d8b06ce23a980c](https://github.com/ruibaby/halo-admin/commit/19f03c2e70c698b985fbffbee81afcbe7193bc9d#diff-c21a683c9d26ae62c62935a90cdf536c2f40970ce7c73eddb2d8b06ce23a980c)

这样确实更美观&#x1F44D;

2022-06-08 07:16 UTC, gungnir479 commented on src/views/sheet/independent/LinkList.vue
> +                      <div class="flex-col absolute top-0 right-0" style="justify-content: center">
想问问这里图标具体值什么，是logo吗😂

2022-06-14 09:57 UTC, ruibaby commented
@gungnir479 Hello，此 PR 还在继续吗？是否遇到了什么问题

2022-06-15 13:19 UTC, gungnir479 commented
> @gungnir479 Hello，此 PR 还在继续吗？是否遇到了什么问题

期末考试中&#x1F92F;，本周内应该可以解决
以及再问下关于这个图标的问题https://github.com/halo-dev/halo-admin/pull/574#discussion_r892002308

2022-06-16 03:25 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                      <div class="flex-col absolute top-0 right-0" style="justify-content: center">
> 想问问这里图标具体值什么，是logo吗😂

这里说的是将编辑和删除这两个按钮合并成一个 dropdown，因为这两个按钮有点占用空间。可以看这里的示例：https://github.com/halo-dev/halo-admin/pull/574#issuecomment-1145719043

2022-06-16 03:26 UTC, ruibaby commented
> 期末考试中🤯，本周内应该可以解决
> 以及再问下关于这个图标的问题https://github.com/halo-dev/halo-admin/pull/574#discussion_r892002308

这个 PR 可以慢慢来，应该会被放在 1.6.x 的 milestone 中。

2022-07-12 15:03 UTC, JohnNiang commented
/ping @halo-dev/sig-halo-admin

2022-07-13 06:56 UTC, gungnir479 commented
抱歉忘记提醒了，已经提交了修改 [commit](https://github.com/halo-dev/halo-admin/pull/574/commits/69db6f89606b14bda563b941792348ac58f16b9d) &#x1F625;

2022-07-26 02:55 UTC, ruibaby requested changes

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +                        <p class="truncate text-sm font-medium text-gray-900 truncate">
这里的 p 标签会有一个 padding 的样式设置，会导致如下情况：

<img width="800" alt="image" src="https://user-images.githubusercontent.com/21301288/180911749-7b3ceed3-998f-4f8c-97af-4ad792a70b54.png">

可以改为这样：

```vue
<div class="flex flex-col gap-y-1.5">
  <p class="mb-0 truncate text-sm font-medium text-gray-900 truncate">
    {{ link.name }}
  </p>
  <p class="mb-0 truncate text-sm text-gray-500">{{ link.description }}</p>
</div>
```

<img width="753" alt="image" src="https://user-images.githubusercontent.com/21301288/180912059-6b80659a-6437-4e22-985f-ed08fe2624cc.png">

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/components/LinkCreateModal.vue
> +    dragOptions() {
这个 computed 似乎没有被用到。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
>  const columns = [
此 PR 修改之后，这个 columns 已经没有用处了，建议删掉。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +    handleClose() {
未使用的函数，建议删掉。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +.link {
未使用的类名。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +.list-group-item-body {
未使用的类名。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +.link {
未使用的类名。

2022-07-26 02:55 UTC, ruibaby commented on src/views/sheet/independent/LinkList.vue
> +      console.log(this.form)
未使用的 console.log 建议移除，或者使用 `this.$log.debug` 代替。

2022-07-26 02:56 UTC, ruibaby commented
另外，再没有数据的时候建议添加一个提示，目前如果没有添加过友情链接，那么页面会是空白。

<img width="1690" alt="Snipaste_2022-07-26_10-39-48" src="https://user-images.githubusercontent.com/21301288/180913372-e372e560-f2b2-4bd9-a0c3-c59ce32be712.png">

可以参考日志管理：

<img width="1689" alt="Snipaste_2022-07-26_10-40-00" src="https://user-images.githubusercontent.com/21301288/180913400-fb448cdd-9361-4a02-9684-f117424dd5c0.png">

2022-07-31 09:53 UTC, ruibaby reviewed
/approve

2022-07-31 09:53 UTC, ruibaby commented
/milestone 1.6.x

/cc @halo-dev/sig-halo-admin

2022-07-31 09:57 UTC, ruibaby commented
/hold

@gungnir479 请更新一下 @halo-dev/admin-api 的版本为 `1.1.0`，否则无法使用在 https://github.com/halo-dev/halo/pull/2105 中更改的 API。

2022-07-31 09:58 UTC, ruibaby commented
/retitle feat: links and link groups support drag and drop sorting

2022-07-31 15:21 UTC, JohnNiang reviewed
经过手动测试发现，编辑友联后点击“保存”按钮会出现如下错误：

<img width="340" alt="image" src="https://user-images.githubusercontent.com/16865714/182033330-a579f74d-ec7a-4b99-b1b4-bc75b5a8a197.png">

2022-07-31 15:31 UTC, gungnir479 commented
> 经过手动测试发现，编辑友联后点击“保存”按钮会出现如下错误：
> 
> <img alt="image" width="340" src="https://user-images.githubusercontent.com/16865714/182033330-a579f74d-ec7a-4b99-b1b4-bc75b5a8a197.png">

收到，正在排查。

2022-08-01 12:21 UTC, guqing reviewed
显示器 13.3 英寸 出现一下字体溢出问题，应换行显示
![image](https://user-images.githubusercontent.com/38999863/182146516-a7c6e469-a817-44f7-8eb6-c4638f64e948.png)

2022-08-01 12:27 UTC, guqing commented
修改友链有问题，改的所有值都不生效

2022-08-01 12:31 UTC, ruibaby commented
> 显示器 13.3 英寸 出现以下字体溢出问题，期望换行显示 ![image](https://user-images.githubusercontent.com/38999863/182146516-a7c6e469-a817-44f7-8eb6-c4638f64e948.png)

@gungnir479 在 https://github.com/halo-dev/halo-admin/pull/574/files#diff-c21a683c9d26ae62c62935a90cdf536c2f40970ce7c73eddb2d8b06ce23a980cR61 加上 `override-hidden` 即可。

2022-08-01 13:52 UTC, gungnir479 commented
> 修改友链分组有问题，无法修改其值，现象是只要输入了分组会导致表单的所有值都无法更新 ![image](https://user-images.githubusercontent.com/38999863/182148133-728125ff-

> 修改友链分组有问题，无法修改其值，现象是只要输入了分组会导致表单的所有值都无法更新 ![image](https://user-images.githubusercontent.com/38999863/182148133-728125ff-cb33-4d88-838a-81f28a973fe2.png)

原因是修改的分组（如1111）目前不存在。正在处理这种情况。

2022-08-04 03:20 UTC, JohnNiang commented
/cc @halo-dev/sig-halo-admin

2022-08-04 13:33 UTC, cetr commented
![image](https://user-images.githubusercontent.com/49756728/182859222-bb382161-28e5-4c32-aee3-13e61b3a6318.png)

这个鼠标感应区域太小，稍微给点宽度

2022-08-05 02:47 UTC, guqing commented
经测试没发现问题
/lgtm

2022-08-05 13:14 UTC, ruibaby commented
/unhold

感谢 @gungnir479 的贡献。

2022-08-05 13:14 UTC, ruibaby approved these changes

2022-08-05 13:16 UTC, merged

2022-08-05 13:22 UTC, gungnir479 commented
感谢各位开发者的指导！