fix: cannot set journal page size
halo-dev/halo-admin pull request #601
Opened 2022-09-01 05:33 UTC by JustinLiang522

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

修复了无法设置日志、相册、链接页标题和每页显示条数的Bug

#### Which issue(s) this PR fixes:

Fixes #2366
Fixes #2339

#### Special notes for your reviewer:

2022-09-01 05:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo-admin?pullRequest=601) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo-admin?pullRequest=601) it.</sub>

2022-09-01 06:28 UTC, JohnNiang commented
/cc @halo-dev/sig-halo-admin

2022-09-01 07:35 UTC, guqing commented
hi @JustinLiang522 感谢你的贡献，需要先点击徽标签署一下CLA https://github.com/halo-dev/halo-admin/pull/601#issuecomment-1233761783

2022-09-01 10:57 UTC, ruibaby requested changes

2022-09-01 10:57 UTC, ruibaby commented on src/views/sheet/independent/JournalList.vue
> +const keys = ['journals_page_size', 'journals_title']
可以不用在外面定义，直接在方法写就可以了。

> 不影响此 PR 合并。

2022-09-01 10:59 UTC, ruibaby requested changes
之前在 data 定义的 options 初始值是一个空数组，可以改为对象形式。

https://github.com/halo-dev/halo-admin/blob/bbd810d308358acab12c15b6209a71caa4f13345/src/views/sheet/independent/JournalList.vue#L232

2022-09-01 12:43 UTC, ruibaby approved these changes
/approve

2022-09-01 15:05 UTC, guqing reviewed
/lgtm

2022-09-01 15:51 UTC, ruibaby commented
/milestone 1.5.x

2022-09-01 15:51 UTC, ruibaby commented
/cherry-pick release-1.4

2022-09-01 15:51 UTC, ruibaby commented
/cherry-pick release-1.5

2022-09-01 15:56 UTC, merged

2022-11-23 14:15 UTC, JohnNiang commented
/cherrypick release-1.6